import type { Metadata } from "next";
import SideBar from "../ui/SideBar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BookStoreLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <div className="flex flex-row">
        <SideBar />
        {children}
      </div>
    </div>
  );
}
